[project]
name = "cloud-storage-client-api"
version = "0.1.0"
description = "Abstract cloud storage client base class (ABC)"
requires-python = ">=3.14"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
